### ISSUE TITLE
More frequent dashboard updates

### ISSUE THREAD

**Issue by RSully** [toddwschneider/nyc-subway-turnstile-data#7]
Per the readme

> Data updates weekly on Saturday mornings

Is this an automated process? It would be great if this updated daily or every 2 days via a job, especially right now as NYC enters phase 2.

**Comment by toddwschneider** [comment]
@RSully yes it is automated, but the MTA's website only updates once per week, on Saturday mornings. Unless you know of somewhere else to get the data from, I don't think your suggestion is possible. I'm going to close this issue but lmk if other questions, thanks

**Comment by RSully** [comment]
Ah sorry, did not notice that!
